const express = require("express");
const auth = require("../middleware/auth.js");
const router = express.Router();
const GameController = require("../controller/GameController");

router.get("/", GameController.getAllGames);
router.get("/:id_games", GameController.getGameById);
router.post("/", auth, GameController.createGame);
router.delete("/:id_games", auth, GameController.deleteGameById);
router.patch("/:id_games", auth, GameController.updateGame);
router.put("/:id_games", auth, GameController.updateGame);
router.get("/name/:name", GameController.getGameByName);

module.exports = router;
/**
 * @swagger
 * components:
 *   schemas:
 *     Games:
 *       type: object
 *       required:
 *         - name
 *         - release_date
 *         - genres
 *         - platforms
 *         - publisher
 *         - max_players
 *       properties:
 *         id:
 *           type: string
 *           description: Autogenerated id
 *         name:
 *           type: string
 *           description: The name of the game
 *         release_date:
 *           type: string
 *           format: date
 *           description: Release date of the game in the original country
 *         genres:
 *           type: array
 *           items:
 *             type: string
 *           description: Genres of the game
 *         platforms:
 *           type: array
 *           items:
 *             type: string
 *           description: The platforms available to play the game
 *         publisher:
 *           type: string
 *         max_players:
 *           type: integer
 *           description: Maximum number of players
 *
 * tags:
 *   - name: Games
 *     description: Game management
 *
 * paths:
 *   /games:
 *     post:
 *       summary: Add a game to the list
 *       tags:
 *         - Games
 *       requestBody:
 *         required: true
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/Games'
 *       responses:
 *         201:
 *           description: The created game
 *           content:
 *             application/json:
 *               schema:
 *                 $ref: '#/components/schemas/Games'
 *         500:
 *           description: Some server error
 *     get:
 *       summary: All the games
 *       tags:
 *         - Games
 *       responses:
 *         200:
 *           description: All the games
 *           content:
 *             application/json:
 *               schema:
 *                 type: array
 *                 items:
 *                   $ref: '#/components/schemas/Games'
 *         500:
 *           description: Some server error
 *
 *   /games/{id_games}:
 *     get:
 *       summary: Get a game by id
 *       tags:
 *         - Games
 *       parameters:
 *         - in: path
 *           name: id_games
 *           required: true
 *           schema:
 *             type: string
 *       responses:
 *         200:
 *           description: The game
 *           content:
 *             application/json:
 *               schema:
 *                 $ref: '#/components/schemas/Games'
 *         404:
 *           description: Game not found
 *         500:
 *           description: Some server error
 *     patch:
 *       summary: Partially update a game by id
 *       tags:
 *         - Games
 *       parameters:
 *         - in: path
 *           name: id_games
 *           required: true
 *           schema:
 *             type: string
 *       requestBody:
 *         required: true
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/Games'
 *       responses:
 *         200:
 *           description: The updated game
 *           content:
 *             application/json:
 *               schema:
 *                 $ref: '#/components/schemas/Games'
 *         404:
 *           description: Game not found
 *         500:
 *           description: Some server error
 *     put:
 *       summary: Replace a game by id
 *       tags:
 *         - Games
 *       parameters:
 *         - in: path
 *           name: id_games
 *           required: true
 *           schema:
 *             type: string
 *       requestBody:
 *         required: true
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/Games'
 *       responses:
 *         200:
 *           description: The replaced game
 *           content:
 *             application/json:
 *               schema:
 *                 $ref: '#/components/schemas/Games'
 *         404:
 *           description: Game not found
 *         500:
 *           description: Some server error
 *     delete:
 *       summary: Delete a game by id
 *       tags:
 *         - Games
 *       parameters:
 *         - in: path
 *           name: id_games
 *           required: true
 *           schema:
 *             type: string
 *       responses:
 *         204:
 *           description: Game deleted successfully
 *         404:
 *           description: Game not found
 *         500:
 *           description: Some server error

 *   /games/name/{name}:
 *     get:
 *       summary: Get a game by name
 *       tags:
 *         - Games
 *       parameters:
 *         - in: path
 *           name: name
 *           required: true
 *           schema:
 *             type: string
 *       responses:
 *         200:
 *           description: The matching game(s)
 *           content:
 *             application/json:
 *               schema:
 *                 type: array
 *                 items:
 *                   $ref: '#/components/schemas/Games'
 *         404:
 *           description: No game found with that name
 *         500:
 *           description: Some server error
 */