const express = require("express");
const auth = require("../middleware/auth.js");
const router = express.Router();
const RewardsController = require("../controller/RewardsController.js");

// Classic CRUD routes
router.post("/", auth, RewardsController.createReward);
// router.delete("/:id", auth, RewardsController.deleteRewardById);
// router.patch("/:id", auth, RewardsController.updateReward);
// router.put("/:id", auth, RewardsController.updateReward);

module.exports = router;
/**
 * @swagger
 * components:
 *   schemas:
 *     Reward:
 *       type: object
 *       required:
 *         - title
 *         - description
 *         - tournament_id
 *       properties:
 *         id:
 *           type: string
 *           description: Autogenerated id
 *         title:
 *           type: string
 *           description: Short title of the reward
 *         description:
 *           type: string
 *           description: Detailed description of the reward
 *         tournament_id:
 *           type: string
 *           description: Associated tournament id
 *         team_id:
 *           type: string
 *           nullable: true
 *           description: Associated team id (if any)
 *
 * tags:
 *   - name: Rewards
 *     description: Rewards management
 *
 * paths:
 *   /rewards:
 *     post:
 *       summary: Create a reward
 *       tags:
 *         - Rewards
 *       requestBody:
 *         required: true
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/Reward'
 *       responses:
 *         201:
 *           description: Reward created
 *           content:
 *             application/json:
 *               schema:
 *                 $ref: '#/components/schemas/Reward'
 *         400:
 *           description: Validation error
 *         500:
 *           description: Some server error
 *
 *   /rewards/{id}:
 *     get:
 *       summary: Get a reward by id
 *       tags:
 *         - Rewards
 *       parameters:
 *         - in: path
 *           name: id
 *           required: true
 *           schema:
 *             type: string
 *       responses:
 *         200:
 *           description: The reward
 *           content:
 *             application/json:
 *               schema:
 *                 $ref: '#/components/schemas/Reward'
 *         404:
 *           description: Reward not found
 *         500:
 *           description: Some server error
 *     delete:
 *       summary: Delete a reward by id
 *       tags:
 *         - Rewards
 *       parameters:
 *         - in: path
 *           name: id
 *           required: true
 *           schema:
 *             type: string
 *       responses:
 *         204:
 *           description: Reward deleted successfully
 *         404:
 *           description: Reward not found
 *         500:
 *           description: Some server error
 */