const express = require("express");
const auth = require("../middleware/auth.js");
const router = express.Router();
const TeamsController = require("../controller/TeamsController");
const RewardsController = require("../controller/RewardsController.js");

// classic CRUD routes
router.get("/", TeamsController.getAllTeams);
router.get("/:id", TeamsController.getTeamsById);
router.post("/", TeamsController.createTeam);
router.delete("/:id", TeamsController.deleteTeamsById);
router.patch("/:id", TeamsController.updateTeams);
// routes for getting players and rewards in a team
router.get("/:id/players", TeamsController.getPlayersInTeam);
router.get("/:id/rewards", RewardsController.getRewardsInTeam);

module.exports = router;
/**
 * @swagger
 * components:
 *   schemas:
 *     Teams:
 *       type: object
 *       required:
 *         - name
 *         - favorite_game
 *       properties:
 *         id:
 *           type: string
 *           description: Autogenerated id
 *         name:
 *           type: string
 *           description: The name of the team
 *         favorite_game:
 *           type: string
 *           description: The favorite game of the team (game id)
 *         teammates:
 *           type: array
 *           items:
 *             type: string
 *           description: Array of user ids in the team
 *         creation_date:
 *           type: string
 *           format: date
 *           description: Creation date of the team
 *         nationality:
 *           type: string
 *           description: Nationality of the team
 *
 * tags:
 *   - name: Teams
 *     description: Team management
 *
 * paths:
 *   /teams:
 *     post:
 *       summary: Add a team to the list
 *       tags:
 *         - Teams
 *       requestBody:
 *         required: true
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/Teams'
 *       responses:
 *         201:
 *           description: The created team
 *           content:
 *             application/json:
 *               schema:
 *                 $ref: '#/components/schemas/Teams'
 *         500:
 *           description: Some server error
 *     get:
 *       summary: All the teams
 *       tags:
 *         - Teams
 *       responses:
 *         200:
 *           description: All the teams
 *           content:
 *             application/json:
 *               schema:
 *                 type: array
 *                 items:
 *                   $ref: '#/components/schemas/Teams'
 *         500:
 *           description: Some server error
 *
 *   /teams/{id}:
 *     get:
 *       summary: Get a team by id
 *       tags:
 *         - Teams
 *       parameters:
 *         - in: path
 *           name: id
 *           required: true
 *           schema:
 *             type: string
 *       responses:
 *         200:
 *           description: The team
 *           content:
 *             application/json:
 *               schema:
 *                 $ref: '#/components/schemas/Teams'
 *         404:
 *           description: Team not found
 *         500:
 *           description: Some server error
 *     patch:
 *       summary: Partially update a team by id
 *       tags:
 *         - Teams
 *       parameters:
 *         - in: path
 *           name: id
 *           required: true
 *           schema:
 *             type: string
 *       requestBody:
 *         required: true
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/Teams'
 *       responses:
 *         200:
 *           description: The updated team
 *           content:
 *             application/json:
 *               schema:
 *                 $ref: '#/components/schemas/Teams'
 *         404:
 *           description: Team not found
 *         500:
 *           description: Some server error
 *     put:
 *       summary: Replace a team by id
 *       tags:
 *         - Teams
 *       parameters:
 *         - in: path
 *           name: id
 *           required: true
 *           schema:
 *             type: string
 *       requestBody:
 *         required: true
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/Teams'
 *       responses:
 *         200:
 *           description: The replaced team
 *           content:
 *             application/json:
 *               schema:
 *                 $ref: '#/components/schemas/Teams'
 *         404:
 *           description: Team not found
 *         500:
 *           description: Some server error
 *     delete:
 *       summary: Delete a team by id
 *       tags:
 *         - Teams
 *       parameters:
 *         - in: path
 *           name: id
 *           required: true
 *           schema:
 *             type: string
 *       responses:
 *         204:
 *           description: Team deleted successfully
 *         404:
 *           description: Team not found
 *         500:
 *           description: Some server error
 *
 *   /teams/{id}/players:
 *     get:
 *       summary: Get players in a team
 *       tags:
 *         - Teams
 *       parameters:
 *         - in: path
 *           name: id
 *           required: true
 *           schema:
 *             type: string
 *       responses:
 *         200:
 *           description: Array of user ids (players) in the team
 *           content:
 *             application/json:
 *               schema:
 *                 type: array
 *                 items:
 *                   $ref: '#/components/schemas/Users'
 *         404:
 *           description: Team not found
 *         500:
 *           description: Some server error
 *
 *   /teams/{id}/rewards:
 *     get:
 *       summary: Get rewards assigned to a team
 *       tags:
 *         - Teams
 *         - Rewards
 *       parameters:
 *         - in: path
 *           name: id
 *           required: true
 *           schema:
 *             type: string
 *       responses:
 *         200:
 *           description: Array of rewards for the team
 *           content:
 *             application/json:
 *               schema:
 *                 type: array
 *                 items:
 *                   $ref: '#/components/schemas/Reward'
 *         404:
 *           description: Team not found
 *         500:
 *           description: Some server error
 */