const express = require("express");
const auth = require("../middleware/auth.js");
const router = express.Router();
const TeamsController = require("../controller/TeamsController");

router.get("/", TeamsController.getAllTeams);
router.get("/:id", TeamsController.getTeamsById);
router.post("/", TeamsController.createTeam);
router.delete("/:id", TeamsController.deleteTeamsById);
router.patch("/:id", TeamsController.updateTeams);

module.exports = router;

/**
 * @swagger
 * components:
 *   schemas:
 *     Teams:
 *       type: object
 *       required:
 *         - name
 *         - favorite_game
 *         - teammates
 *         - creation_date
 *         - nationality
 *       properties:
 *         id:
 *           type: ObjectId
 *           description: Autogenerated id
 *         name:
 *           type: string
 *           description: The name of the team
 *         favorite_game:
 *           type: string
 *           description: The favorite game of the team
 *         teammates:
 *           type: string
 *           items:
 *             type: string
 *           description: Teammates of the team
 *         creation_date:
 *           type: string
 *           format: date
 *           description: Creation date of the team
 *         nationality:
 *           type: string
 *           description: Nationality of the team
 *
 * tags:
 *   - name: Teams
 *     description: team management
 *
 * paths:
 *   /Teams:
 *     post:
 *       summary: Add a team to the list
 *       tags:
 *         - Teams
 *       requestBody:
 *         required: true
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/Teams'
 *       responses:
 *         201:
 *           description: The created team
 *           content:
 *             application/json:
 *               schema:
 *                 $ref: '#/components/schemas/Teams'
 *         500:
 *           description: Some server error
 *     get:
 *       summary: All the Teams
 *       tags:
 *         - Teams
 *       responses:
 *         200:
 *           description: All the Teams
 *           content:
 *             application/json:
 *               schema:
 *                 type: array
 *                 items:
 *                   $ref: '#/components/schemas/Teams'
 *         500:
 *           description: Some server error
 *
 *   /Teams/{id}:
 *     get:
 *       summary: Get a team by id
 *       tags:
 *         - Teams
 *       parameters:
 *         - in: path
 *           name: id
 *           required: true
 *           schema:
 *             type: string
 *       responses:
 *         200:
 *           description: The team
 *           content:
 *             application/json:
 *               schema:
 *                 $ref: '#/components/schemas/Teams'
 *         404:
 *           description: team not found
 *         500:
 *           description: Some server error
 *     patch:
 *       summary: Partially update a team by id
 *       tags:
 *         - Teams
 *       parameters:
 *         - in: path
 *           name: id
 *           required: true
 *           schema:
 *             type: string
 *       requestBody:
 *         required: true
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/Teams'
 *       responses:
 *         200:
 *           description: The updated team
 *           content:
 *             application/json:
 *               schema:
 *                 $ref: '#/components/schemas/Teams'
 *         404:
 *           description: team not found
 *         500:
 *           description: Some server error
 *     put:
 *       summary: Replace a team by id
 *       tags:
 *         - Teams
 *       parameters:
 *         - in: path
 *           name: id
 *           required: true
 *           schema:
 *             type: string
 *       requestBody:
 *         required: true
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/Teams'
 *       responses:
 *         200:
 *           description: The replaced team
 *           content:
 *             application/json:
 *               schema:
 *                 $ref: '#/components/schemas/Teams'
 *         404:
 *           description: team not found
 *         500:
 *           description: Some server error
 *     delete:
 *       summary: Delete a team by id
 *       tags:
 *         - Teams
 *       parameters:
 *         - in: path
 *           name: id
 *           required: true
 *           schema:
 *             type: string
 *       responses:
 *         204:
 *           description: team deleted successfully
 *         404:
 *           description: team not found
 *         500:
 *           description: Some server error

 *   /Teams/name/{name}:
 *     get:
 *       summary: Get a team by name
 *       tags:
 *         - Teams
 *       parameters:
 *         - in: path
 *           name: name
 *           required: true
 *           schema:
 *             type: string
 *       responses:
 *         200:
 *           description: The matching team(s)
 *           content:
 *             application/json:
 *               schema:
 *                 type: array
 *                 items:
 *                   $ref: '#/components/schemas/Teams'
 *         404:
 *           description: No team found with that name
 *         500:
 *           description: Some server error
 */