const express = require("express");
const router = express.Router();
const TournamentsController = require("../controller/TournamentsController");
const RewardsController = require("../controller/RewardsController");
const auth = require("../middleware/auth.js");

// Classic CRUD routes
router.get("/", TournamentsController.getAllTournaments);
router.get("/:tournament_id", TournamentsController.getTournamentById);
router.post("/", TournamentsController.createTournament);
router.patch("/:tournament_id", auth, TournamentsController.updateTournament);
router.put("/:tournament_id", auth, TournamentsController.updateTournament);
router.delete("/:tournament_id", auth, TournamentsController.deleteTournament);

router.get("/:tournament_id/teams", TournamentsController.getTeamsInTournament);
router.get("/:tournament_id/teams/:team_id", TournamentsController.getPlayersInTeam);

router.get("/:tournament_id/rewards", RewardsController.getRewardsInTournament);
router.get("/:tournament_id/teams/:team_id/rewards", RewardsController.getRewardsInTeam);
// /tournaments/{id}/players
// /tournaments/{id}/jury

// /tournaments/{id}/teams/{id_team}/players	Yes owner	Ajouter un teammate
// /tournaments/{id}/teams/{id_team}/players		

module.exports = router;


/**
 * @swagger
 * components:
 *   schemas:
 *     Tournaments:
 *       type: object
 *       required:
 *         - name
 *         - place_name
 *         - capacity
 *         - start_date
 *         - end_date
 *         - status
 *         - specialized_game
 *       properties:
 *         id:
 *           type: string
 *           description: Autogenerated id
 *         name:
 *           type: string
 *           description: The name of the tournament
 *         place_name:
 *           type: string
 *           description: Venue or place name
 *         capacity:
 *           type: object
 *           description: Capacity details (e.g., seats, teams)
 *         equipment:
 *           type: array
 *           items:
 *             type: string
 *           description: Required equipment list
 *         start_date:
 *           type: string
 *           format: date
 *         end_date:
 *           type: string
 *           format: date
 *         status:
 *           type: string
 *         specialized_game:
 *           type: string
 *           description: Reference id to the `Games` resource
 *         registred_teams:
 *           type: array
 *           items:
 *             type: string
 *           description: Array of registered team ids
 *
 *     Team:
 *       type: object
 *       required:
 *         - id
 *         - name
 *       properties:
 *         id:
 *           type: string
 *           description: Autogenerated id
 *         name:
 *           type: string
 *           description: Team name
 *         members:
 *           type: array
 *           items:
 *             type: string
 *           description: Array of user ids registered in the team
 *         captain:
 *           type: string
 *           description: User id of the team captain
 *
 *     Reward:
 *       type: object
 *       required:
 *         - id
 *         - title
 *         - description
 *         - tournament_id
 *       properties:
 *         id:
 *           type: string
 *           description: Autogenerated id
 *         title:
 *           type: string
 *           description: Short title of the reward
 *         description:
 *           type: string
 *           description: Detailed description of the reward
 *         tournament_id:
 *           type: string
 *           description: Associated tournament id
 *         team_id:
 *           type: string
 *           nullable: true
 *           description: Associated team id (if any)
 * tags:
 *   - name: Tournaments
 *     description: Tournaments management
 *   - name: Teams
 *     description: Teams management within tournaments
 *   - name: Rewards
 *     description: Rewards management within tournaments
 *
 * paths:
 *   /tournaments:
 *     post:
 *       summary: Add a tournament to the list
 *       tags:
 *         - Tournaments
 *       requestBody:
 *         required: true
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/Tournaments'
 *       responses:
 *         201:
 *           description: The created tournament
 *           content:
 *             application/json:
 *               schema:
 *                 $ref: '#/components/schemas/Tournaments'
 *         500:
 *           description: Some server error
 *     get:
 *       summary: All the tournaments
 *       tags:
 *         - Tournaments
 *       responses:
 *         200:
 *           description: All the tournaments
 *           content:
 *             application/json:
 *               schema:
 *                 type: array
 *                 items:
 *                   $ref: '#/components/schemas/Tournaments'
 *         500:
 *           description: Some server error
 *
 *   /tournaments/{tournament_id}:
 *     get:
 *       summary: Get a tournament by id
 *       tags:
 *         - Tournaments
 *       parameters:
 *         - in: path
 *           name: tournament_id
 *           required: true
 *           schema:
 *             type: string
 *       responses:
 *         200:
 *           description: The tournament
 *           content:
 *             application/json:
 *               schema:
 *                 $ref: '#/components/schemas/Tournaments'
 *         404:
 *           description: Tournament not found
 *         500:
 *           description: Some server error
 *     patch:
 *       summary: Partially update a tournament by id
 *       tags:
 *         - Tournaments
 *       parameters:
 *         - in: path
 *           name: tournament_id
 *           required: true
 *           schema:
 *             type: string
 *       requestBody:
 *         required: true
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/Tournaments'
 *       responses:
 *         200:
 *           description: The updated tournament
 *           content:
 *             application/json:
 *               schema:
 *                 $ref: '#/components/schemas/Tournaments'
 *         404:
 *           description: Tournament not found
 *         500:
 *           description: Some server error
 *     put:
 *       summary: Replace a tournament by id
 *       tags:
 *         - Tournaments
 *       parameters:
 *         - in: path
 *           name: tournament_id
 *           required: true
 *           schema:
 *             type: string
 *       requestBody:
 *         required: true
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/Tournaments'
 *       responses:
 *         200:
 *           description: The replaced tournament
 *           content:
 *             application/json:
 *               schema:
 *                 $ref: '#/components/schemas/Tournaments'
 *         404:
 *           description: Tournament not found
 *         500:
 *           description: Some server error
 *     delete:
 *       summary: Delete a tournament by id
 *       tags:
 *         - Tournaments
 *       parameters:
 *         - in: path
 *           name: tournament_id
 *           required: true
 *           schema:
 *             type: string
 *       responses:
 *         204:
 *           description: Tournament deleted successfully
 *         404:
 *           description: Tournament not found
 *         500:
 *           description: Some server error
 *
 *   /tournaments/{tournament_id}/teams:
 *     get:
 *       summary: Get all teams registered in a tournament
 *       tags:
 *         - Tournaments
 *         - Teams
 *       parameters:
 *         - in: path
 *           name: tournament_id
 *           required: true
 *           schema:
 *             type: string
 *       responses:
 *         200:
 *           description: Array of teams in the tournament
 *           content:
 *             application/json:
 *               schema:
 *                 type: array
 *                 items:
 *                   $ref: '#/components/schemas/Team'
 *         404:
 *           description: Tournament not found
 *         500:
 *           description: Some server error
 *
 *   /tournaments/{tournament_id}/rewards:
 *     get:
 *       summary: Get all rewards for a tournament
 *       tags:
 *         - Tournaments
 *         - Rewards
 *       parameters:
 *         - in: path
 *           name: tournament_id
 *           required: true
 *           schema:
 *             type: string
 *       responses:
 *         200:
 *           description: Array of rewards for the tournament
 *           content:
 *             application/json:
 *               schema:
 *                 type: array
 *                 items:
 *                   $ref: '#/components/schemas/Reward'
 *         404:
 *           description: Tournament not found
 *         500:
 *           description: Some server error
 *
 *   /tournaments/{tournament_id}/teams/{team_id}/rewards:
 *     get:
 *       summary: Get rewards for a specific team in a tournament
 *       tags:
 *         - Tournaments
 *         - Rewards
 *       parameters:
 *         - in: path
 *           name: tournament_id
 *           required: true
 *           schema:
 *             type: string
 *         - in: path
 *           name: team_id
 *           required: true
 *           schema:
 *             type: string
 *       responses:
 *         200:
 *           description: Array of rewards for the team in the tournament
 *           content:
 *             application/json:
 *               schema:
 *                 type: array
 *                 items:
 *                   $ref: '#/components/schemas/Reward'
 *         404:
 *           description: Tournament or Team not found
 *         500:
 *           description: Some server error
 */