const express = require("express");
const router = express.Router();
const TournamentsController = require("../controller/TournamentsController");
const auth = require("../middleware/auth.js");

router.get("/", TournamentsController.getAllTournaments);
router.get("/:tournament_id", TournamentsController.getTournamentById);
router.post("/", TournamentsController.createTournament);
router.patch("/:tournament_id", auth, TournamentsController.updateTournament);
router.put("/:tournament_id", auth, TournamentsController.updateTournament);
router.delete("/:tournament_id", auth, TournamentsController.deleteTournament);
// router.get("/:tournament_id/teams", TournamentsController.getTeamsInTournament)
// /tournaments/{id}/rewards
// /tournaments/{id}/players
// /tournaments/{id}/jury
// /tournaments/{id}/teams/{id_team}/players	X	Voir une équipe dans un tournoi
// /tournaments/{id}/teams/{id_team}/players	Yes owner	Ajouter un teammate
// /tournaments/{id}/teams/{id_team}/players		

module.exports = router;


/**
 * @swagger
 * components:
 *   schemas:
 *     Tournaments:
 *       type: object
 *       required:
 *         - name
 *         - place_name
 *         - capacity
 *         - start_date
 *         - end_date
 *         - status
 *         - specialized_game
 *       properties:
 *         id:
 *           type: string
 *           description: Autogenerated id
 *         name:
 *           type: string
 *           description: The name of the tournament
 *         place_name:
 *           type: string
 *           description: Venue or place name
 *         capacity:
 *           type: object
 *           description: Capacity details (e.g., seats, teams)
 *         equipment:
 *           type: array
 *           items:
 *             type: string
 *           description: Required equipment list
 *         start_date:
 *           type: string
 *           format: date
 *         end_date:
 *           type: string
 *           format: date
 *         status:
 *           type: string
 *         specialized_game:
 *           type: string
 *           description: Reference id to the `Games` resource
 *         registred_teams:
 *           type: array
 *           items:
 *             type: string
 *           description: Array of registered team ids
 *
 * tags:
 *   - name: Tournaments
 *     description: Tournaments management
 *
 * paths:
 *   /tournaments:
 *     post:
 *       summary: Add a tournament to the list
 *       tags:
 *         - Tournaments
 *       requestBody:
 *         required: true
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/Tournaments'
 *       responses:
 *         201:
 *           description: The created tournament
 *           content:
 *             application/json:
 *               schema:
 *                 $ref: '#/components/schemas/Tournaments'
 *         500:
 *           description: Some server error
 *     get:
 *       summary: All the tournaments
 *       tags:
 *         - Tournaments
 *       responses:
 *         200:
 *           description: All the tournaments
 *           content:
 *             application/json:
 *               schema:
 *                 type: array
 *                 items:
 *                   $ref: '#/components/schemas/Tournaments'
 *         500:
 *           description: Some server error
 *
 *   /tournaments/{tournament_id}:
 *     get:
 *       summary: Get a tournament by id
 *       tags:
 *         - Tournaments
 *       parameters:
 *         - in: path
 *           name: tournament_id
 *           required: true
 *           schema:
 *             type: string
 *       responses:
 *         200:
 *           description: The tournament
 *           content:
 *             application/json:
 *               schema:
 *                 $ref: '#/components/schemas/Tournaments'
 *         404:
 *           description: Tournament not found
 *         500:
 *           description: Some server error
 *     patch:
 *       summary: Partially update a tournament by id
 *       tags:
 *         - Tournaments
 *       parameters:
 *         - in: path
 *           name: tournament_id
 *           required: true
 *           schema:
 *             type: string
 *       requestBody:
 *         required: true
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/Tournaments'
 *       responses:
 *         200:
 *           description: The updated tournament
 *           content:
 *             application/json:
 *               schema:
 *                 $ref: '#/components/schemas/Tournaments'
 *         404:
 *           description: Tournament not found
 *         500:
 *           description: Some server error
 *     put:
 *       summary: Replace a tournament by id
 *       tags:
 *         - Tournaments
 *       parameters:
 *         - in: path
 *           name: tournament_id
 *           required: true
 *           schema:
 *             type: string
 *       requestBody:
 *         required: true
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/Tournaments'
 *       responses:
 *         200:
 *           description: The replaced tournament
 *           content:
 *             application/json:
 *               schema:
 *                 $ref: '#/components/schemas/Tournaments'
 *         404:
 *           description: Tournament not found
 *         500:
 *           description: Some server error
 *     delete:
 *       summary: Delete a tournament by id
 *       tags:
 *         - Tournaments
 *       parameters:
 *         - in: path
 *           name: tournament_id
 *           required: true
 *           schema:
 *             type: string
 *       responses:
 *         204:
 *           description: Tournament deleted successfully
 *         404:
 *           description: Tournament not found
 *         500:
 *           description: Some server error
 */