const express = require("express");
const router = express.Router();
const UsersController = require("../controller/UsersController");
const auth = require("../middleware/auth.js");
const upload = require("../middleware/uploads.js");

router.post(
  "/signup",
  upload.single('avatar'), // same name as in user Controller
  UsersController.signupNewUser
);

router.post("/login", UsersController.loginUser);
router.patch(
  "/:id",
  auth,
  upload.single('avatar'), // update avatar
  UsersController.updateUser
);

router.delete("/:id", auth, UsersController.deleteUser);

module.exports = router;


/**
 * @swagger
 * components:
 *   schemas:
 *     Users:
 *       type: object
 *       required:
 *         - firstname
 *         - lastname
 *         - email
 *         - password
 *       properties:
 *         id:
 *           type: string
 *           description: Autogenerated id
 *         firstname:
 *           type: string
 *         lastname:
 *           type: string
 *         email:
 *           type: string
 *           format: email
 *         status:
 *           type: string
 *           enum:
 *             - spectator
 *             - jury
 *             - player
 *             - admin
 *         favorite_game:
 *           type: string
 *           description: Reference id to a Game
 *         team_role:
 *           type: string
 *         year_joining_team:
 *           type: string
 *           format: date
 *         nationality:
 *           type: string
 *         specialty:
 *           type: array
 *           items:
 *             type: string
 *         team_id:
 *           type: string
 *
 * tags:
 *   - name: Users
 *     description: User management
 *
 * paths:
 *   /users/signup:
 *     post:
 *       summary: Register a new user
 *       tags:
 *         - Users
 *       requestBody:
 *         required: true
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/Users'
 *       responses:
 *         201:
 *           description: User created
 *           content:
 *             application/json:
 *               schema:
 *                 $ref: '#/components/schemas/Users'
 *         400:
 *           description: Validation error
 *         500:
 *           description: Some server error
 *
 *   /users/login:
 *     post:
 *       summary: Log in a user
 *       tags:
 *         - Users
 *       requestBody:
 *         required: true
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 email:
 *                   type: string
 *                   format: email
 *                 password:
 *                   type: string
 *       responses:
 *         200:
 *           description: Authentication successful
 *           content:
 *             application/json:
 *               schema:
 *                 type: object
 *                 properties:
 *                   token:
 *                     type: string
 *         401:
 *           description: Invalid credentials
 *         500:
 *           description: Some server error
 *
 *   /users/{id}:
 *     put:
 *       summary: Replace a user by id
 *       tags:
 *         - Users
 *       parameters:
 *         - in: path
 *           name: id
 *           required: true
 *           schema:
 *             type: string
 *       requestBody:
 *         required: true
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/Users'
 *       responses:
 *         200:
 *           description: The replaced user
 *           content:
 *             application/json:
 *               schema:
 *                 $ref: '#/components/schemas/Users'
 *         404:
 *           description: User not found
 *         500:
 *           description: Some server error
 *     patch:
 *       summary: Partially update a user by id
 *       tags:
 *         - Users
 *       parameters:
 *         - in: path
 *           name: id
 *           required: true
 *           schema:
 *             type: string
 *       requestBody:
 *         required: true
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/Users'
 *       responses:
 *         200:
 *           description: The updated user
 *           content:
 *             application/json:
 *               schema:
 *                 $ref: '#/components/schemas/Users'
 *         404:
 *           description: User not found
 *         500:
 *           description: Some server error
 *     delete:
 *       summary: Delete a user by id
 *       tags:
 *         - Users
 *       parameters:
 *         - in: path
 *           name: id
 *           required: true
 *           schema:
 *             type: string
 *       responses:
 *         204:
 *           description: User deleted successfully
 *         404:
 *           description: User not found
 *         500:
 *           description: Some server error
 */